### ISSUE TITLE
Additional pods in error state after some time

### ISSUE THREAD

**Issue by muemi03** [CAAPIM/layer7-operator#64]
Dear Team.
I have setup a very simple environment in GKE, 3 simple gateways using github repositories as their source of truth.
Initially everything was running fine. "kubectl get all" looked like:

> $ kubectl get all
> NAME                                                      READY   STATUS    RESTARTS   AGE
> pod/gw1-dev-57649b7f7d-cxfkd                              1/1     Running   0          23h
> pod/gw1-prod-597c58c7c6-rtmjv                             1/1     Running   0          89m
> pod/gw1-test-5f9c7f74fb-7b767                             1/1     Running   0          52m
> pod/layer7-operator-controller-manager-5975b7664c-7zpnr   1/1     Running   0          23h
> 
> NAME                                                         TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)                         AGE
> service/gw1-dev                                              LoadBalancer   34.118.238.197   34.57.163.101    8443:30799/TCP,9443:32150/TCP   23h
> service/gw1-prod                                             LoadBalancer   34.118.229.76    34.58.244.213    8443:32139/TCP,9443:30913/TCP   22h
> service/gw1-test                                             LoadBalancer   34.118.226.216   34.170.188.176   8443:31083/TCP,9443:31760/TCP   22h
> service/layer7-operator-controller-manager-metrics-service   ClusterIP      34.118.235.133   <none>           8443/TCP                        23h
> 
> NAME                                                 READY   UP-TO-DATE   AVAILABLE   AGE
> deployment.apps/gw1-dev                              1/1     1            1           23h
> deployment.apps/gw1-prod                             1/1     1            1           22h
> deployment.apps/gw1-test                             1/1     1            1           22h
> deployment.apps/layer7-operator-controller-manager   1/1     1            1           23h
> 
> NAME                                                            DESIRED   CURRENT   READY   AGE
> replicaset.apps/gw1-dev-57649b7f7d                              1         1         1       23h
> replicaset.apps/gw1-prod-597c58c7c6                             1         1         1       22h
> replicaset.apps/gw1-test-5f9c7f74fb                             1         1         1       22h
> replicaset.apps/layer7-operator-controller-manager-5975b7664c   1         1         1       23h

However, I observed, now the second time, that overnight, obviously after some time, it looks like:

> $ kubectl get all
> NAME                                                      READY   STATUS                   RESTARTS   AGE
> pod/gw1-dev-57649b7f7d-bl4d4                              1/1     Running                  0          8h
> pod/gw1-dev-57649b7f7d-cxfkd                              0/1     ContainerStatusUnknown   1          37h
> pod/gw1-prod-597c58c7c6-2k9f2                             0/1     Error                    0          8h
> pod/gw1-prod-597c58c7c6-msnx9                             0/1     ContainerStatusUnknown   1          12h
> pod/gw1-prod-597c58c7c6-p9lbf                             1/1     Running                  0          75m
> pod/gw1-prod-597c58c7c6-rtmjv                             0/1     ContainerStatusUnknown   1          16h
> pod/gw1-test-5f9c7f74fb-7b767                             0/1     ContainerStatusUnknown   1          15h
> pod/gw1-test-5f9c7f74fb-7mj97                             1/1     Running                  0          4h44m
> pod/gw1-test-5f9c7f74fb-bwt9m                             0/1     Error                    0          9h
> pod/gw1-test-5f9c7f74fb-nkxjs                             0/1     ContainerStatusUnknown   1          11h
> pod/layer7-operator-controller-manager-5975b7664c-7zpnr   1/1     Running                  0          37h
> 
> NAME                                                         TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)                         AGE
> service/gw1-dev                                              LoadBalancer   34.118.238.197   34.57.163.101    8443:30799/TCP,9443:32150/TCP   37h
> service/gw1-prod                                             LoadBalancer   34.118.229.76    34.58.244.213    8443:32139/TCP,9443:30913/TCP   37h
> service/gw1-test                                             LoadBalancer   34.118.226.216   34.170.188.176   8443:31083/TCP,9443:31760/TCP   37h
> service/layer7-operator-controller-manager-metrics-service   ClusterIP      34.118.235.133   <none>           8443/TCP                        37h
> 
> NAME                                                 READY   UP-TO-DATE   AVAILABLE   AGE
> deployment.apps/gw1-dev                              1/1     1            1           37h
> deployment.apps/gw1-prod                             1/1     1            1           37h
> deployment.apps/gw1-test                             1/1     1            1           37h
> deployment.apps/layer7-operator-controller-manager   1/1     1            1           37h
> 
> NAME                                                            DESIRED   CURRENT   READY   AGE
> replicaset.apps/gw1-dev-57649b7f7d                              1         1         1       37h
> replicaset.apps/gw1-prod-597c58c7c6                             1         1         1       37h
> replicaset.apps/gw1-test-5f9c7f74fb                             1         1         1       37h
> replicaset.apps/layer7-operator-controller-manager-5975b7664c   1         1         1       37h

No change in github repos during that time.
I attached the controller logs.

Any idea, whats going wrong?
Thanks
...Michael
[layer7-operator-controller-manager-5975b7664c-7zpnr.log](https://github.com/user-attachments/files/19359905/layer7-operator-controller-manager-5975b7664c-7zpnr.log)

**Comment by Gazza7205** [comment]
Could you provide some more details of the configuration that you have?
- Kubernetes Version
- Node sizes (cpu/memory)
- Gateway CR Configuration (resources)

Are you removing or scaling down your node pools at night or do they run 24/7?

**Comment by muemi03** [comment]
This is what I found for version:

>  kubectl version
> Client Version: v1.31.6-dispatcher
> Kustomize Version: v5.4.2
> Server Version: v1.31.6-gke.1020000

k8s cluster runs in GKE's autopilot mode.

> $ kubectl get nodes
> NAME                                  STATUS   ROLES    AGE    VERSION
> gk3-l7-cluster-pool-2-a4a1a140-m8hv   Ready    <none>   2d1h   v1.31.6-gke.1020000
> gk3-l7-cluster-pool-2-d8abe46c-cjzz   Ready    <none>   2d1h   v1.31.6-gke.1020000
> 

The gateway configuration looks very simple and the same for all three gateways, just differ by repo branch names.

```
apiVersion: security.brcmlabs.com/v1
kind: Gateway
metadata:
  name: gw1-dev
spec:
  version: "11.1.1"
  license:
    accept: true
    secretName: gateway-license
  app:
    replicas: 1
    image: docker.io/caapim/gateway:11.1.1
    management:
      graphman:
        enabled: true
      username: admin
      password: 7layer
      cluster:
        password: 7layer
        hostname: gw1.home.com
    service:
      type: LoadBalancer
      ports:
      - name: https
        port: 8443
        targetPort: 8443
        protocol: TCP
      - name: management
        port: 9443
        targetPort: 9443
        protocol: TCP
    repositoryReferences:
      - name: repo-gw1-config-dev
        enabled: true
        type: dynamic
      - name: repo-gw1-code-dev
        enabled: true
        type: dynamic

```
