### ISSUE TITLE
Issue connecting to Azure Devops

### ISSUE THREAD

**Issue by rnulll** [CAAPIM/layer7-operator#69]
Hi there,

I might not be in the right location to raise an "issue" but here goes. From our development environment we are able to connect to a Github repository and deploy graphman bundles onto our pods. We seem to face an issue with connecting to Azure Devops seeing our repository is there. When connecting to the specific endpoint we get the following:` "error":"invalid pkt-len found"` .  When altering the url to a higher level it gives the following:` "error":"repository not found"`. I tried editing the scope of the rights linked to the PAT i'm using but to no avail.

For context, the URL is shaped as such: https://dev.azure.com/company/_git/reponame?path=/folder1/subfolder1 - could it be that I need to alter my repository yaml to reflect the possible difference between azure and git?

I'm using the following yaml for it.

```
apiVersion: security.brcmlabs.com/v1
kind: Repository
metadata:
  name: l7-dev-gw
spec:
  enabled: true
  type: git
  endpoint: https://dev.azure.com/company/_git/reponame?path=/folder1/subfolder1
  branch: main
  auth:
    type: basic
    existingSecretName: company-repository-auth
```

Hope you can help out!
